\documentclass[12pt]{article}
\usepackage{fullpage}
\pagestyle{empty}
\newif\ifincludeQuality
\newif\ifincludeHash
\newif\ifincludeKmerHash
\newif\ifuseLandscape

\useLandscapefalse
\includeHashfalse
\includeKmerHashfalse
\includeQualityfalse

\Sexpr{if (exists("landscape") && landscape) "\\useLandscapetrue"}
\Sexpr{if (is(x, "FASTQSummary")) "\\includeQualitytrue"}

\ifuseLandscape
\usepackage[landscape,margin=0.5in]{geometry}
\else
\usepackage[margin=0.5in]{geometry}
\fi

\renewcommand{\familydefault}{\sfdefault}

\title{Sequence Quality Report from \texttt{qrqc}}
\author{}
\date{\today}

\begin{document}

\maketitle

<<setup,include=FALSE,cache=FALSE>>=
fig.dir <- file.path(outdir, "figures/")
tex.opts <- qrqc_options$tex_opts
opts <- opts_chunk$set(fig.path=fig.dir, fig.align='center', 
                       fig.width=tex.opts[[orientation]]$fig.width, 
                       fig.height=tex.opts[[orientation]]$fig.height)
@ 
\thispagestyle{empty}
\section[]{General Information}
<<filetable,echo=FALSE,results="asis">>=
tbl <- fileTable(x)
print(xtable(tbl), include.rownames=FALSE)
@ 
\newpage

\section[]{Quick Summary}
<<summary,echo=FALSE>>=
summaryPlot(x)
@ 

\newpage
\ifincludeQuality
\section[]{Sequence Quality}
<<qualplot,echo=FALSE,warning=FALSE,message=FALSE>>=
qualPlot(x)
@ 
\newpage
\fi

\section[]{Nucleotide Proportion by Position}
<<baseplot,echo=FALSE,warning=FALSE,message=FALSE>>=
basePlot(x, type="proportion")
@ 
\newpage

\section[]{N Frequency by Position}
<<Nfreq,echo=FALSE,warning=FALSE,message=FALSE>>=
basePlot(x, bases='N', type="proportion")
@ 
\newpage

\section[]{GC Content by Position}
<<GCfreq,echo=FALSE,warning=FALSE,message=FALSE>>=
gcPlot(x)
@ 
\newpage

\section{Sequence Length}
<<seqlen,echo=FALSE,warning=FALSE,message=FALSE>>=
seqlenPlot(x)
@ 
\newpage

\Sexpr{if (exists("include.hash") && include.hash) "\\includeHashtrue"}
\ifincludeHash
\subsection{Most Frequent Sequences}

<<hashed,echo=FALSE,warning=FALSE,message=FALSE,results="asis">>=
tbl <- makeHashTable(x)
print(xtable(tbl), include.rownames=FALSE, size="tiny")
@ 
\fi
\newpage

\Sexpr{if (exists("include.kmers") && include.kmers) "\\includeKmerHashtrue"}

\ifincludeKmerHash
\section{Positional k-mer Abundance}
<<kmerHashed,echo=FALSE,warning=FALSE,message=FALSE>>=
kmerKLPlot(x)
@ 
\fi
\newpage

\section{Session Information}
<<sessionInfo,echo=FALSE,warning=FALSE,message=FALSE>>=
sessionInfo()
@ 


\end{document}
