\documentclass[12pt]{article}
\usepackage{fullpage}
\pagestyle{empty}
\newif\ifincludeHash
\newif\ifincludeKmerHash
\newif\ifuseLandscape
\useLandscapefalse
\includeHashfalse
\includeKmerHashfalse
<<landscape,echo=FALSE,results="asis">>=
if (exists("landscape") && landscape)
  cat("\\useLandscapetrue")
@
\ifuseLandscape
\usepackage[landscape,margin=0.5in]{geometry}
\else
\usepackage[margin=0.5in]{geometry}
\fi

\renewcommand{\familydefault}{\sfdefault}

\title{Sequence Quality Report from \texttt{qrqc}}
\author{}
\date{\today}

\begin{document}

\maketitle

<<setup,include=FALSE,cache=FALSE>>=
fig.dir <- file.path(outdir, "fig")
opts <- opts_chunk$set(fig.path=fig.dir, fig.align='center', 
                  fig.width=FIG.WIDTH, fig.height=FIG.HEIGHT)
@ 
\thispagestyle{empty}
\section[]{General Information}
<<filetable,include=FALSE,cache=FALSE,message=FALSE,results="asis">>=
fileTable(x)
@ 
\newpage

\section[]{Sequence Quality}
<<qualplot,echo=FALSE,warning=FALSE,message=FALSE>>=
qualPlot(x)
@ 
\newpage

\section[]{Nucleotide Proportion by Position}
<<baseplot,echo=FALSE,warning=FALSE,message=FALSE>>=
basePlot(x, type="proportion")
@ 
\newpage

\section[]{N Frequency by Position}
<<Nfreq,echo=FALSE,warning=FALSE,message=FALSE>>=
#basePlot(x, bases='N')
@ 
\newpage

\section[]{GC Content by Position}
<<GCfreq,echo=FALSE,warning=FALSE,message=FALSE>>=
gcPlot(x)
@ 
\newpage

\section{Sequence Length}
<<seqlen,echo=FALSE,warning=FALSE,message=FALSE>>=
seqlenPlot(x)
@ 
\newpage

<<includeHash,echo=FALSE,warning=FALSE,message=FALSE,results="asis">>=
if (exists("include.hash") && include.hash)
  cat("\\includeHashtrue")
@ 
\ifincludeHash
\subsection{Most Frequent Sequences}
<<hashed,echo=FALSE,warning=FALSE,message=FALSE,results="asis">>=
cat(makeHashTable(x))
@ 
\fi
\newpage

<<includeKmerHash,echo=FALSE,warning=FALSE,message=FALSE,results="asis">>=
if (exists("include.kmers") && include.kmers)
  cat("\\includeKmerHashtrue")
@ 

\ifincludeKmerHash
\section{Positional k-mer Abundance}
<<kmerHashed,echo=FALSE,warning=FALSE,message=FALSE>>=
kmerKLPlot(x)
@ 
\fi
\newpage

\end{document}
